# Check datasets

In [1]:
import pandas as pd

pubmed = pd.read_csv('data/pubmed_mesh/train_multilabel.csv')
pubmed

,pmid,title,year,spanish_abstract,level1_codes,level1_names,level2_codes,level2_names,major_subjects_count,level1_categories_str,...,category_Diseases,category_Geographicals,category_Health_Care,category_Humanities,category_Information_Science,category_Named_Groups,category_Organisms,category_Phenomena_and_Processes,category_Psychiatry_and_Psychology,category_Technology_Industry_Agriculture
0,21709969,La industria farmacéutica y la sostenibilidad ...,2011.0,La crisis económica mundial y su impacto en la...,"['I', 'J', 'N']","['Anthropology, Education, Sociology and Socia...","['I01', 'J01', 'N04', 'N05']","['Social Sciences', 'Technology, Industry, and...",3,"Anthropology, Education, Sociology and Social ...",...,0,0,1,0,0,0,0,0,0,1
1,22481725,Discapacidad funcional de individuos adultos c...,2012.0,El objetivo fue investigar el grado de Discapa...,"['E', 'I', 'N']","['Analytical, Diagnostic and Therapeutic Techn...","['E01', 'E02', 'I03', 'N02']","['Diagnosis', 'Therapeutics', 'Human Activitie...",2,"Analytical, Diagnostic and Therapeutic Techniq...",...,0,0,1,0,0,0,0,0,0,0
2,36862933,Bíceps distales ruptura braquii en un paciente...,2022.0,INTRODUCCIÓN: La lesión del tendón del bíceps ...,"['A', 'C']","['Anatomy', 'Diseases']","['A02', 'C01', 'C08', 'C26']","['Musculoskeletal System', 'Infections', 'Resp...",3,Anatomy; Diseases,...,1,0,0,0,0,0,0,0,0,0
3,34181841,Ictericia obstructiva secundaria a úlcera duod...,2021.0,INTRODUCCIÓN: Las úlceras pépticas son lesione...,['C'],['Diseases'],"['C06', 'C23']","['Digestive System Diseases', 'Pathological Co...",2,Diseases,...,1,0,0,0,0,0,0,0,0,0
4,18813585,Instituciones y conflictos en la enseñanza de ...,2008.0,El objetivo de este trabajo es analizar el pro...,"['C', 'I', 'N']","['Diseases', 'Anthropology, Education, Sociolo...","['C01', 'I02', 'N02']","['Infections', 'Education', 'Health Care Facil...",3,"Diseases; Anthropology, Education, Sociology a...",...,1,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18595,17683697,Análisis de las características mecánicas-acús...,2007.0,INTRODUCCIÓN Y OBJETIVO: La cirugía de reempla...,"['E', 'H']","['Analytical, Diagnostic and Therapeutic Techn...","['E04', 'H01']","['Surgical Procedures, Operative', 'Natural Sc...",2,"Analytical, Diagnostic and Therapeutic Techniq...",...,0,0,0,0,0,0,0,0,0,0
18596,33399663,Revisión sistemática de patógenos virales y ba...,2020.0,El conocimiento de los agentes patógenos prese...,"['B', 'C']","['Organisms', 'Diseases']","['B01', 'C01', 'C22']","['Eukaryota', 'Infections', 'Animal Diseases']",2,Organisms; Diseases,...,1,0,0,0,0,0,1,0,0,0
18597,38131659,Érase una vez un lugar donde aprendimos a escu...,2023.0,Las respuestas gubernamentales a la pandemia C...,"['C', 'N']","['Diseases', 'Health Care']","['C01', 'C08', 'N06']","['Infections', 'Respiratory Tract Diseases', '...",2,Diseases; Health Care,...,1,0,1,0,0,0,0,0,0,0
18598,21548253,Artroplastia total de rodilla con inserción ti...,2011.0,INTRODUCCIÓN: No existe un criterio único para...,['E'],"['Analytical, Diagnostic and Therapeutic Techn...","['E04', 'E07']","['Surgical Procedures, Operative', 'Equipment ...",2,"Analytical, Diagnostic and Therapeutic Techniq...",...,0,0,0,0,0,0,0,0,0,0
18599,37358176,Eficiencia del sistema de salud chileno: análi...,2022.0,ANTECEDENTES: La evaluación de la eficiencia d...,['N'],['Health Care'],"['N01', 'N04']","['Population Characteristics', 'Health Service...",2,Health Care,...,0,0,1,0,0,0,0,0,0,0

In [2]:
pubmed.columns

Index(['pmid', 'title', 'year', 'spanish_abstract', 'level1_codes',
       'level1_names', 'level2_codes', 'level2_names', 'major_subjects_count',
       'level1_categories_str', 'level2_categories_str', 'title_processed',
       'spanish_abstract_processed',
       'category_Analytical_Diagnostic_and_Therapeutic_Techniques_and_Equipment',
       'category_Anatomy',
       'category_Anthropology_Education_Sociology_and_Social_Phenomena',
       'category_Chemicals_and_Drugs', 'category_Disciplines_and_Occupations',
       'category_Diseases', 'category_Geographicals', 'category_Health_Care',
       'category_Humanities', 'category_Information_Science',
       'category_Named_Groups', 'category_Organisms',
       'category_Phenomena_and_Processes',
       'category_Psychiatry_and_Psychology',
       'category_Technology_Industry_Agriculture'],
      dtype='object')

In [17]:
import pandas as pd

anat = pd.read_json('results/anat_em_beto.json')
anat_robertas = pd.read_json('results/anat_em_robertas.json')
anat_robertas_2 = pd.read_json('results/anat_em_robertas_2.json')
anat_sci = pd.read_json('results/anat_em_robertas_sci.json')
anat_xlm = pd.read_json('results/anat_em_robertas_xlm.json')

anat = pd.concat([anat, anat_robertas], ignore_index=True)
anat = pd.concat([anat, anat_robertas_2], ignore_index=True)
anat = pd.concat([anat, anat_sci], ignore_index=True)
anat = pd.concat([anat, anat_xlm], ignore_index=True)

anat = anat.sort_values(by="test_f1", ascending=False).reset_index(drop=True)
anat

,model_name,batch_size,learning_rate,epochs,weight_decay,warmup_ratio,lr_scheduler,best_checkpoint,val_accuracy,val_f1,val_precision,val_recall,test_accuracy,test_f1,test_precision,test_recall
0,FacebookAI/xlm-roberta-large,16,0.00002,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-large_bs...,0.975543,0.644713,0.628110,0.662218,0.968092,0.647326,0.639566,0.655276
1,FacebookAI/xlm-roberta-large,16,0.00003,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-large_bs...,0.974979,0.640629,0.625329,0.656696,0.967475,0.643099,0.637432,0.648868
2,Flaglab/SciBETO-large,16,0.00003,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-large_bs16_lr3e...,0.975343,0.636811,0.620148,0.654395,0.968664,0.642645,0.637779,0.647587
3,FacebookAI/xlm-roberta-large,16,0.00001,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-large_bs...,0.975856,0.639511,0.629118,0.650253,0.967066,0.637507,0.630776,0.644383
4,FacebookAI/xlm-roberta-large,16,0.00001,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-large_bs...,0.974666,0.635635,0.615883,0.656696,0.966648,0.634034,0.621234,0.647373
5,beto,16,0.00002,10,0.1,0.06,linear,models/anat_em_beto_bs16_lr2e-05/checkpoint-3708,0.974038,0.621902,0.609272,0.635067,0.966439,0.627047,0.624259,0.629859
6,Flaglab/SciBETO-large,16,0.00001,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-large_bs16_lr1e...,0.973823,0.620278,0.596432,0.646111,0.967620,0.626981,0.612424,0.642247
7,Flaglab/SciBETO-large,16,0.00002,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-large_bs16_lr2e...,0.974403,0.623250,0.602752,0.645191,0.967266,0.626182,0.616212,0.636480
8,beto,16,0.00003,10,0.1,0.06,linear,models/anat_em_beto_bs16_lr3e-05/checkpoint-3296,0.973584,0.617530,0.594883,0.641970,0.965695,0.624661,0.610522,0.639470
9,Flaglab/SciBETO-large,32,0.00001,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-large_bs32_lr1e...,0.973886,0.620432,0.594766,0.648412,0.966694,0.621574,0.606961,0.636907
10,bertin-project/bertin-roberta-base-spanish,16,0.00003,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.972657,0.610254,0.601790,0.618960,0.965686,0.621109,0.620051,0.622170
11,bertin-project/bertin-roberta-base-spanish,16,0.00003,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.972657,0.610254,0.601790,0.618960,0.965686,0.621109,0.620051,0.622170
12,FacebookAI/xlm-roberta-base,16,0.00003,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-base_bs1...,0.971926,0.602837,0.581445,0.625863,0.964678,0.618166,0.615678,0.620675
13,Flaglab/SciBETO-base,16,0.00003,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs16_lr3e-...,0.973133,0.610284,0.598408,0.622642,0.965504,0.617843,0.612335,0.623452
14,Flaglab/SciBETO-base,16,0.00003,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs16_lr3e-...,0.973133,0.610284,0.598408,0.622642,0.965504,0.617843,0.612335,0.623452
15,Flaglab/SciBETO-base,16,0.00002,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs16_lr2e-...,0.973023,0.614458,0.596362,0.633686,0.965513,0.617383,0.610612,0.624306
16,Flaglab/SciBETO-base,16,0.00002,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs16_lr2e-...,0.973023,0.614458,0.596362,0.633686,0.965513,0.617383,0.610612,0.624306
17,beto,32,0.00003,10,0.1,0.06,linear,models/anat_em_beto_bs32_lr3e-05/checkpoint-1442,0.973208,0.617120,0.594123,0.641970,0.965559,0.616742,0.606737,0.627082
18,beto,16,0.00001,10,0.1,0.06,linear,models/anat_em_beto_bs16_lr1e-05/checkpoint-2472,0.973412,0.617780,0.606020,0.630005,0.965722,0.615664,0.615993,0.615335
19,FacebookAI/xlm-roberta-base,16,0.00002,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-base_bs1...,0.972396,0.606420,0.580632,0.634607,0.964796,0.615239,0.604829,0.626015
20,beto,32,0.00002,10,0.1,0.06,linear,models/anat_em_beto_bs32_lr2e-05/checkpoint-1030,0.973646,0.610569,0.601968,0.619420,0.965695,0.614072,0.613027,0.615122
21,Flaglab/SciBETO-base,16,0.00001,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs16_lr1e-...,0.972757,0.601202,0.582399,0.621261,0.965658,0.613381,0.608102,0.618753
22,Flaglab/SciBETO-base,32,0.00002,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs32_lr2e-...,0.973603,0.609823,0.602697,0.617119,0.965622,0.610560,0.609844,0.611277
23,Flaglab/SciBETO-base,32,0.00002,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs32_lr2e-...,0.973603,0.609823,0.602697,0.617119,0.965622,0.610560,0.609844,0.611277
24,Flaglab/SciBETO-base,32,0.00003,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs32_lr3e-...,0.973306,0.605897,0.592952,0.619420,0.965250,0.609950,0.605901,0.614054
25,Flaglab/SciBETO-base,32,0.00003,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs32_lr3e-...,0.973306,0.605897,0.592952,0.619420,0.965250,0.609950,0.605901,0.614054
26,FacebookAI/xlm-roberta-base,32,0.00003,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-base_bs3...,0.971331,0.599048,0.565075,0.637368,0.964133,0.609723,0.592346,0.628150
27,FacebookAI/xlm-roberta-base,32,0.00002,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-base_bs3...,0.970548,0.588743,0.553977,0.628164,0.963352,0.600372,0.581168,0.620889
28,Flaglab/SciBETO-base,16,0.00001,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs16_lr1e-...,0.972976,0.601619,0.588132,0.615739,0.964732,0.598965,0.592152,0.605938
29,Flaglab/SciBETO-base,32,0.00001,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs32_lr1e-...,0.971973,0.596221,0.570408,0.624482,0.964560,0.598394,0.584675,0.612772
30,Flaglab/SciBETO-base,32,0.00001,10,0.1,0.06,linear,models/anat_em_Flaglab_SciBETO-base_bs32_lr1e-...,0.971973,0.596221,0.570408,0.624482,0.964560,0.598394,0.584675,0.612772
31,bertin-project/bertin-roberta-base-spanish,16,0.00002,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.972171,0.592609,0.577225,0.608836,0.963924,0.595325,0.584482,0.606578
32,bertin-project/bertin-roberta-base-spanish,16,0.00002,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.972171,0.592609,0.577225,0.608836,0.963924,0.595325,0.584482,0.606578
33,bertin-project/bertin-roberta-base-spanish,32,0.00003,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.972312,0.593800,0.584150,0.603774,0.963724,0.595195,0.589889,0.600598
34,bertin-project/bertin-roberta-base-spanish,32,0.00003,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.972312,0.593800,0.584150,0.603774,0.963724,0.595195,0.589889,0.600598
35,FacebookAI/xlm-roberta-base,16,0.00001,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-base_bs1...,0.969984,0.579117,0.544094,0.618960,0.962262,0.594115,0.575055,0.614481
36,beto,32,0.00001,10,0.1,0.06,linear,models/anat_em_beto_bs32_lr1e-05/checkpoint-1854,0.972285,0.593778,0.574130,0.614818,0.963298,0.589045,0.575770,0.602947
37,bertin-project/bertin-roberta-base-spanish,32,0.00002,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.971481,0.585993,0.565199,0.608376,0.963125,0.587272,0.570479,0.605083
38,bertin-project/bertin-roberta-base-spanish,32,0.00002,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.971481,0.585993,0.565199,0.608376,0.963125,0.587272,0.570479,0.605083
39,bertin-project/bertin-roberta-base-spanish,16,0.00001,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.971058,0.578058,0.566196,0.590428,0.963016,0.582518,0.573886,0.591414
40,bertin-project/bertin-roberta-base-spanish,16,0.00001,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.971058,0.578058,0.566196,0.590428,0.963016,0.582518,0.573886,0.591414
41,FacebookAI/xlm-roberta-base,32,0.00001,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-base_bs3...,0.967542,0.537768,0.503820,0.576622,0.961218,0.561436,0.537171,0.587997
42,bertin-project/bertin-roberta-base-spanish,32,0.00001,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.970338,0.559746,0.552714,0.566958,0.961754,0.551848,0.545739,0.558095
43,bertin-project/bertin-roberta-base-spanish,32,0.00001,10,0.1,0.06,linear,models/anat_em_bertin-project_bertin-roberta-b...,0.970338,0.559746,0.552714,0.566958,0.961754,0.551848,0.545739,0.558095

In [18]:
anat_xlm

,model_name,batch_size,learning_rate,epochs,weight_decay,warmup_ratio,lr_scheduler,best_checkpoint,val_accuracy,val_f1,val_precision,val_recall,test_accuracy,test_f1,test_precision,test_recall
0,FacebookAI/xlm-roberta-large,16,0.00002,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-large_bs...,0.975543,0.644713,0.628110,0.662218,0.968092,0.647326,0.639566,0.655276
1,FacebookAI/xlm-roberta-large,16,0.00003,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-large_bs...,0.974979,0.640629,0.625329,0.656696,0.967475,0.643099,0.637432,0.648868
2,FacebookAI/xlm-roberta-large,16,0.00001,10,0.1,0.06,linear,models/anat_em_FacebookAI_xlm-roberta-large_bs...,0.974666,0.635635,0.615883,0.656696,0.966648,0.634034,0.621234,0.647373

In [19]:
pubmed = pd.read_json('results/pubmed_beto.json')
pubmed_robertas = pd.read_json('results/pubmed_robertas.json')
pubmed_robertas_2 = pd.read_json('results/pubmed_robertas_2.json')

pubmed = pd.concat([pubmed, pubmed_robertas], ignore_index=True)
pubmed = pd.concat([pubmed, pubmed_robertas_2], ignore_index=True)

pubmed = pubmed.sort_values(by="test_exact_match", ascending=False).reset_index(drop=True)
pubmed

,model_name,batch_size,learning_rate,epochs,weight_decay,warmup_ratio,lr_scheduler,best_checkpoint,val_exact_match,val_f1_micro,val_f1_macro,test_exact_match,test_f1_micro,test_f1_macro
0,Flaglab/SciBETO-base,16,0.00001,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-base_bs16_lr1e-0...,0.318280,0.662022,0.532342,0.339928,0.673428,0.548137
1,Flaglab/SciBETO-base,16,0.00002,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-base_bs16_lr2e-0...,0.329892,0.669833,0.543507,0.338379,0.674987,0.557579
2,Flaglab/SciBETO-large,16,0.00001,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-large_bs16_lr1e-...,0.324516,0.674687,0.559434,0.335799,0.686312,0.567912
3,beto,16,0.00002,10,0.1,0.06,linear,models/pubmed_beto_bs16_lr2e-05/checkpoint-4652,0.327097,0.655551,0.530027,0.333219,0.671717,0.548715
4,Flaglab/SciBETO-large,16,0.00003,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-large_bs16_lr3e-...,0.332043,0.682750,0.580946,0.332186,0.690275,0.585194
5,beto,16,0.00003,10,0.1,0.06,linear,models/pubmed_beto_bs16_lr3e-05/checkpoint-4652,0.326237,0.663294,0.538321,0.331326,0.675409,0.553131
6,Flaglab/SciBETO-large,32,0.00002,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-large_bs32_lr2e-...,0.318710,0.677887,0.573263,0.329262,0.688575,0.586007
7,Flaglab/SciBETO-large,16,0.00002,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-large_bs16_lr2e-...,0.325591,0.679952,0.564357,0.328230,0.691719,0.577074
8,beto,32,0.00001,10,0.1,0.06,linear,models/pubmed_beto_bs32_lr1e-05/checkpoint-2910,0.316989,0.643209,0.506299,0.324961,0.656994,0.519682
9,Flaglab/SciBETO-large,32,0.00001,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-large_bs32_lr1e-...,0.330323,0.677106,0.569199,0.324789,0.685350,0.576378
10,beto,32,0.00002,10,0.1,0.06,linear,models/pubmed_beto_bs32_lr2e-05/checkpoint-2910,0.321505,0.655137,0.535486,0.324617,0.666078,0.545077
11,beto,32,0.00003,10,0.1,0.06,linear,models/pubmed_beto_bs32_lr3e-05/checkpoint-2910,0.324301,0.656205,0.546768,0.318940,0.665146,0.553813
12,beto,16,0.00001,10,0.1,0.06,linear,models/pubmed_beto_bs16_lr1e-05/checkpoint-5815,0.317634,0.656943,0.534375,0.317564,0.662954,0.543484

In [11]:
pubmed_robertas

,model_name,batch_size,learning_rate,epochs,weight_decay,warmup_ratio,lr_scheduler,best_checkpoint,val_exact_match,val_f1_micro,val_f1_macro,test_exact_match,test_f1_micro,test_f1_macro
0,Flaglab/SciBETO-large,16,0.00002,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-large_bs16_lr2e-...,0.325591,0.679952,0.564357,0.328230,0.691719,0.577074
1,Flaglab/SciBETO-large,16,0.00003,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-large_bs16_lr3e-...,0.332043,0.682750,0.580946,0.332186,0.690275,0.585194
2,Flaglab/SciBETO-large,32,0.00002,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-large_bs32_lr2e-...,0.318710,0.677887,0.573263,0.329262,0.688575,0.586007
3,Flaglab/SciBETO-large,16,0.00001,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-large_bs16_lr1e-...,0.324516,0.674687,0.559434,0.335799,0.686312,0.567912
4,Flaglab/SciBETO-large,32,0.00001,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-large_bs32_lr1e-...,0.330323,0.677106,0.569199,0.324789,0.685350,0.576378

In [15]:
pubmed_robertas_2

,model_name,batch_size,learning_rate,epochs,weight_decay,warmup_ratio,lr_scheduler,best_checkpoint,val_exact_match,val_f1_micro,val_f1_macro,test_exact_match,test_f1_micro,test_f1_macro
0,Flaglab/SciBETO-base,16,0.00001,10,0.1,0.06,linear,models/pubmed_Flaglab_SciBETO-base_bs16_lr1e-0...,0.31828,0.662022,0.532342,0.339928,0.673428,0.548137